[package]
name = "lab_opencl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocl = "0.19"
rand = "0.8"
image = "0.24"
env_logger = "0.10"
dotenv = "0.15"
log = "0.4"

